name: Python run

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      # we would want to freeze to see all the packages we need to install if possible and `pip freeze > requirements.txt`
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get all my teams info and store it into a JSON.
        run: python get_my_team.py

      - name: Position sorter + AI results.
        run: python position_sorter.py > data/starter_list/starter_list.txt

      - name: Send results to Discord.
        run: python discord-bot.py
